### ISSUE TITLE
Find a good data set

### ISSUE THREAD

**Issue by darkjinung** [darkjinung/projet-industriel-ecp17#29]
To benchmark NLP libraries we need a common data set

**Comment by AmineIzanami** [comment]
My first suggestion : https://d396qusza40orc.cloudfront.net/phoenixassets/amazon_baby.csv

**Comment by amineds** [comment]
Nice dataset
**Note that ratings are not equally distributed across reviews**. 107k reviews - out of 183K - have rating 5, and 33K have 4.
We should keep it and add others.
**Well done**

**Comment by darkjinung** [comment]
Amazon dataset, only big category, more of a raw dataset to be used with clustering / deep
http://jmcauley.ucsd.edu/data/amazon/

**Comment by darkjinung** [comment]
As suggested by @amineds, we should be using:


**For Classification**

- https://mxnetstorage.blob.core.windows.net/public/nlp/categories_train_big.csv

- https://mxnetstorage.blob.core.windows.net/public/nlp/categories_test_big.csv


**For Sentiment**:

- https://mxnetstorage.blob.core.windows.net/public/nlp/amazon_review_polarity_csv.tar.gz

**Comment by darkjinung** [comment]
After meeting of **15/11/2017**, we will be using the dataset suggested by @amineds.
